# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stu_term', models.CharField(blank=True, max_length=100, null=True)),
                ('course_num', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('course_college', models.CharField(blank=True, max_length=100, null=True)),
                ('course_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('course_major', models.CharField(blank=True, max_length=100, null=True)),
                ('course_point', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.IntegerField(default=0)),
                ('start_num', models.IntegerField(default=0)),
                ('end_num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_stu_id', models.CharField(max_length=20)),
                ('user_stu_pwd', models.CharField(max_length=100)),
                ('yzm_url', models.CharField(blank=True, max_length=200, null=True)),
                ('yzm_text', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
