# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170422_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yzm_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
