# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_num',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_num',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
